export default (fontSize: number = 1) => ({
  palette: {
    themePrimary: "#947dfa",
    themeLighterAlt: "#06050a",
    themeLighter: "#181428",
    themeLight: "#2c254b",
    themeTertiary: "#594b96",
    themeSecondary: "#826edc",
    themeDarkAlt: "#9e8afa",
    themeDark: "#ad9cfb",
    themeDarker: "#c2b6fc",
    neutralLighterAlt: "#282828",
    neutralLighter: "#272727",
    neutralLight: "#252525",
    neutralQuaternaryAlt: "#232323",
    neutralQuaternary: "#212121",
    neutralTertiaryAlt: "#202020",
    neutralTertiary: "#fcfcfc",
    neutralSecondary: "#fcfcfc",
    neutralPrimaryAlt: "#fdfdfd",
    neutralPrimary: "#fafafa",
    neutralDark: "#fefefe",
    black: "#fefefe",
    white: "#282828",
    red: "#a52234",
    yellow: "#ffc107",
    green: "#00833e",
    blue: "#4c6bb3",
  },
  fonts: {
    tiny: { fontSize: Math.round(10 * fontSize) },
    xSmall: { fontSize: Math.round(10 * fontSize) },
    small: { fontSize: Math.round(12 * fontSize) },
    smallPlus: { fontSize: Math.round(12 * fontSize) },
    medium: { fontSize: Math.round(14 * fontSize) },
    mediumPlus: { fontSize: Math.round(16 * fontSize) },
    large: { fontSize: Math.round(18 * fontSize) },
    xLarge: { fontSize: Math.round(20 * fontSize) },
    xLargePlus: { fontSize: Math.round(24 * fontSize) },
    xxLarge: { fontSize: Math.round(28 * fontSize) },
    xxLargePlus: { fontSize: Math.round(32 * fontSize) },
    superLarge: { fontSize: Math.round(42 * fontSize) },
    mega: { fontSize: Math.round(68 * fontSize) },
  },
  spacing: {
    s2: Math.round(4 * fontSize),
    s1: Math.round(8 * fontSize),
    m: Math.round(16 * fontSize),
    l1: Math.round(20 * fontSize),
    l2: Math.round(32 * fontSize),
  },
});
