export default (fontSize: number = 1) => {
  return {
    palette: {
      themePrimary: "#5f3bff",
      themeLighterAlt: "#f9f7ff",
      themeLighter: "#e5e0ff",
      themeLight: "#cfc4ff",
      themeTertiary: "#9f89ff",
      themeSecondary: "#7252ff",
      themeDarkAlt: "#5535e6",
      themeDark: "#482dc2",
      themeDarker: "#35218f",
      neutralLighterAlt: "#f6f6f6",
      neutralLighter: "#f2f2f2",
      neutralLight: "#e8e8e8",
      neutralQuaternaryAlt: "#d8d8d8",
      neutralQuaternary: "#cecece",
      neutralTertiaryAlt: "#c6c6c6",
      neutralTertiary: "#595959",
      neutralSecondary: "#373737",
      neutralPrimaryAlt: "#2f2f2f",
      neutralPrimary: "#000000",
      neutralDark: "#151515",
      black: "#0b0b0b",
      white: "#fdfdfd",
      red: "#a52234",
      yellow: "#ffc107",
      green: "#00833e",
      blue: "#4c6bb3",
    },
    fonts: {
      tiny: { fontSize: Math.round(10 * fontSize) },
      xSmall: { fontSize: Math.round(10 * fontSize) },
      small: { fontSize: Math.round(12 * fontSize) },
      smallPlus: { fontSize: Math.round(12 * fontSize) },
      medium: { fontSize: Math.round(14 * fontSize) },
      mediumPlus: { fontSize: Math.round(16 * fontSize) },
      large: { fontSize: Math.round(18 * fontSize) },
      xLarge: { fontSize: Math.round(20 * fontSize) },
      xLargePlus: { fontSize: Math.round(24 * fontSize) },
      xxLarge: { fontSize: Math.round(28 * fontSize) },
      xxLargePlus: { fontSize: Math.round(32 * fontSize) },
      superLarge: { fontSize: Math.round(42 * fontSize) },
      mega: { fontSize: Math.round(68 * fontSize) },
    },
    spacing: {
      s2: Math.round(4 * fontSize),
      s1: Math.round(8 * fontSize),
      m: Math.round(16 * fontSize),
      l1: Math.round(20 * fontSize),
      l2: Math.round(32 * fontSize),
    },
  };
};
