import { ComponentSchema } from '../types';
import { COUNTER_ROTATE_FIELDS } from '../shared';

export const arcGaugeFaceSchema: ComponentSchema = {
  type: 'arc-gauge-face',
  label: 'Arc Gauge Face',
  icon: 'CircleRing',
  allowChildren: true,
  fields: {
    name:   { label: 'Name', type: 'text' },
    x:      { label: 'X', type: 'slider', min: -1000, max: 5000, section: 'Layout' },
    y:      { label: 'Y', type: 'slider', min: -1000, max: 5000, section: 'Layout' },
    width:  { label: 'Width', type: 'slider', min: 4, max: 5000, section: 'Layout' },
    height: { label: 'Height', type: 'slider', min: 4, max: 5000, section: 'Layout' },
    gaugeStartAngle: { label: 'Start angle (° from east, CW)', type: 'slider', min: 0, max: 360, section: 'Arc' },
    gaugeSweepAngle: { label: 'Sweep angle (°)', type: 'slider', min: 10, max: 360, section: 'Arc' },
    gaugeMinValue: { label: 'Min value', type: 'slider', min: -99999, max: 99999, section: 'Value Range' },
    gaugeMaxValue: { label: 'Max value (static fallback)', type: 'slider', min: 1, max: 99999, section: 'Value Range' },
    gaugeMaxField: { label: 'Max value live field (overrides static)', type: 'text', section: 'Value Range' },
    gaugeMajorInterval: { label: 'Major tick interval', type: 'slider', min: 1, max: 99999, section: 'Gauge Ticks' },
    gaugeMidInterval:   { label: 'Mid tick interval (0 = off)', type: 'slider', min: 0, max: 99999, section: 'Gauge Ticks' },
    gaugeMinorInterval: { label: 'Minor tick interval (0 = off)', type: 'slider', min: 0, max: 99999, section: 'Gauge Ticks' },
    gaugeMajorLen:    { label: 'Major tick length px', type: 'slider', min: 1, max: 200, section: 'Gauge Ticks' },
    gaugeMidLen:      { label: 'Mid tick length px', type: 'slider', min: 1, max: 200, section: 'Gauge Ticks' },
    gaugeMinorLen:    { label: 'Minor tick length px', type: 'slider', min: 1, max: 200, section: 'Gauge Ticks' },
    gaugeMajorWeight: { label: 'Major tick weight', type: 'slider', min: 0.5, max: 20, step: 0.5, section: 'Gauge Ticks' },
    gaugeMidWeight:   { label: 'Mid tick weight', type: 'slider', min: 0.5, max: 20, step: 0.5, section: 'Gauge Ticks' },
    gaugeMinorWeight: { label: 'Minor tick weight', type: 'slider', min: 0.5, max: 20, step: 0.5, section: 'Gauge Ticks' },
    gaugeTickColor:   { label: 'Tick color (hex)', type: 'text', section: 'Gauge Ticks' },
    gaugeTickRadius:  { label: 'Tick radius px (0 = auto)', type: 'slider', min: 0, max: 5000, section: 'Gauge Ticks' },
    gaugeRedlineValue: { label: 'Redline starts at (0 = off)', type: 'slider', min: 0, max: 99999, section: 'Redline' },
    gaugeRedlineColor: { label: 'Redline color (hex)', type: 'text', section: 'Redline' },
    gaugeLabelOffset:   { label: 'Label inset from tick outer edge px', type: 'slider', min: 0, max: 200, section: 'Gauge Labels' },
    gaugeLabelRotate:   { label: 'Rotate labels tangent to arc', type: 'checkbox', section: 'Gauge Labels' },
    gaugeLabelDivisor:  { label: 'Label divisor (e.g. 1000 → 9 not 9000)', type: 'slider', min: 1, max: 100000, section: 'Gauge Labels' },
    gaugeSubLabel:      { label: 'Sub-label text (e.g. ×1000 RPM)', type: 'text', section: 'Gauge Labels' },
    gaugeLabelFont:     { label: 'Label font family', type: 'text', section: 'Gauge Labels' },
    gaugeLabelSize:     { label: 'Label font size px', type: 'slider', min: 4, max: 200, section: 'Gauge Labels' },
    gaugeLabelWeight:   { label: 'Label font weight (normal/bold)', type: 'text', section: 'Gauge Labels' },
    gaugeLabelColor:    { label: 'Label color (hex)', type: 'text', section: 'Gauge Labels' },
    gaugeSubLabelSize:  { label: 'Sub-label font size px', type: 'slider', min: 4, max: 120, section: 'Gauge Labels' },
    gaugeSubLabelColor: { label: 'Sub-label color (hex)', type: 'text', section: 'Gauge Labels' },
    backlit: { label: 'Backlit (shines above night overlay)', type: 'checkbox', section: 'Appearance' },
    ...COUNTER_ROTATE_FIELDS,
  },
};
