import gql from 'graphql-tag';

// Content lives on the dumb `Dashboard` type, reachable only via
// `DashboardEntry.dashboard` — see typiql_types.rs. Entry-level fields
// (id/name/path) are a separate, always-located record.
const DASHBOARD_CONTENT_FIELDS = `
  baseDashType
  canvasWidth
  canvasHeight
  background
  dayNight
  neckFx
  elements
  kioskX
  kioskY
  kioskOpacity
  thumbnailDay
  thumbnailNight
  groupIds
`;

const DASHBOARD_ENTRY_FIELDS = `
  id
  name
  path
  dashboard {
    ${DASHBOARD_CONTENT_FIELDS}
  }
`;

export const GET_DASHBOARDS = gql`
  query getDashboardEntries {
    getDashboardEntries {
      ${DASHBOARD_ENTRY_FIELDS}
    }
  }
`;

// Filter-based get-one generated by the typiql macro — same argument set as
// the list query, first match wins. Used instead of fetching the whole list
// and .find()-ing client-side.
export const GET_DASHBOARD_ENTRY = gql`
  query getDashboardEntry($name: String) {
    getDashboardEntry(name: $name) {
      ${DASHBOARD_ENTRY_FIELDS}
    }
  }
`;

export const ADD_DASHBOARD = gql`
  mutation addDashboard($entry: DashboardEntryInput!, $content: DashboardInput!) {
    addDashboard(entry: $entry, content: $content) {
      ${DASHBOARD_ENTRY_FIELDS}
    }
  }
`;

// Entry-level fields (currently just name/path — the "General" tab's rename
// support) go through the auto-generated updateDashboardEntry mutation;
// content goes through the hand-written updateDashboard below.
export const UPDATE_DASHBOARD_ENTRY = gql`
  mutation updateDashboardEntry($id: String!, $update: DashboardEntryInput!) {
    updateDashboardEntry(id: $id, update: $update) {
      id
      name
      path
    }
  }
`;

export const UPDATE_DASHBOARD = gql`
  mutation updateDashboard($id: String!, $update: DashboardInput!) {
    updateDashboard(id: $id, update: $update) {
      ${DASHBOARD_CONTENT_FIELDS}
    }
  }
`;

export const REMOVE_DASHBOARD = gql`
  mutation removeDashboardEntry($id: String!) {
    removeDashboardEntry(id: $id) {
      id
    }
  }
`;

export const UPLOAD_DASHBOARD_FILE = gql`
  mutation uploadDashboardFile($dashboardId: String!, $name: String!, $data: String!) {
    uploadDashboardFile(dashboardId: $dashboardId, name: $name, data: $data) {
      id
      path
      filename
      url
    }
  }
`;

export const DELETE_DASHBOARD_FILE = gql`
  mutation deleteDashboardFile($dashboardId: String!, $path: String!) {
    deleteDashboardFile(dashboardId: $dashboardId, path: $path)
  }
`;

export const UPLOAD_DASHBOARD_THUMBNAILS = gql`
  mutation uploadDashboardThumbnails($id: String!, $dayData: String, $nightData: String) {
    uploadDashboardThumbnails(id: $id, dayData: $dayData, nightData: $nightData) {
      thumbnailDay
      thumbnailNight
    }
  }
`;

export const DASHBOARD_CHANGED_SUB = gql`
  subscription dashboardEntryChanged($id: String) {
    dashboardEntryChanged(id: $id) {
      operationName
      value {
        ${DASHBOARD_ENTRY_FIELDS}
      }
    }
  }
`;

export const SYNC_DASHBOARD_FILES = gql`
  query syncDashboardFiles($dashboardId: String!) {
    syncDashboardFiles(dashboardId: $dashboardId) {
      id
      path
      filename
      url
    }
  }
`;

const TEMPLATE_FIELDS = `
  id
  name
  gaugeType
  component
  thumbnail
`;

export const GET_TEMPLATES = gql`
  query getDashTemplates {
    getDashTemplates {
      ${TEMPLATE_FIELDS}
    }
  }
`;

export const ADD_TEMPLATE = gql`
  mutation addDashTemplate($values: DashTemplateInput!) {
    addDashTemplate(values: $values) {
      ${TEMPLATE_FIELDS}
    }
  }
`;

export const UPDATE_TEMPLATE = gql`
  mutation updateDashTemplate($id: String!, $update: DashTemplateInput!) {
    updateDashTemplate(id: $id, update: $update) {
      ${TEMPLATE_FIELDS}
    }
  }
`;

export const REMOVE_TEMPLATE = gql`
  mutation removeDashTemplate($id: String!) {
    removeDashTemplate(id: $id) {
      id
    }
  }
`;

export const UPLOAD_TEMPLATE_THUMBNAIL = gql`
  mutation uploadDashTemplateThumbnail($id: String!, $data: String!) {
    uploadDashTemplateThumbnail(id: $id, data: $data) {
      ${TEMPLATE_FIELDS}
    }
  }
`;

export const TEMPLATE_CHANGED_SUB = gql`
  subscription dashTemplateChanged {
    dashTemplateChanged {
      operationName
      value {
        ${TEMPLATE_FIELDS}
      }
    }
  }
`;

export const DASHBOARD_UPDATES_SUB = gql`
  subscription dashboardUpdates {
    dashboardUpdates {
      ... on DashboardEntryChanged {
        operationName
        value {
          ${DASHBOARD_ENTRY_FIELDS}
        }
      }
      ... on DashTemplateChanged {
        operationName
      }
      ... on DeviceDefaultChanged {
        operationName
        value { id deviceName dash group }
      }
      ... on TelemetryEvent {
        frame {
          simStatus simon car track driver
          gLat gLon gVert pitch roll
          speed rpm maxRpm gear throttle brake clutch steering abs brakeBias
          fuel fuelCapacity turboBoost
          tyres { temp pressure slipRatio wear brakeTemp }
          airTemp trackTemp
          lap position numCars courseFlag lapIsValid inPit currentLapSeconds lastLapSeconds
        }
      }
    }
  }
`;

export const GET_BUILTIN_TEMPLATES = gql`
  query getBuiltinTemplates {
    getBuiltinTemplates {
      id
      name
      gaugeType
      component
    }
  }
`;

// Drives the DDController virtual gamepad — see graphql/gamepad.rs. Goes
// over this same GraphQL API rather than a Tauri command, since a dashboard
// rendered in a plain browser (e.g. an actual tablet hitting this app's own
// web server) has no Tauri IPC bridge at all. `watchdog: true` marks a held
// press the caller must keep refreshing (~every 200ms) via GAMEPAD_BUTTON
// again — the server force-releases it if those refreshes stop arriving, so
// a dropped connection can't leave something like a horn stuck on. See
// useGamepadButton.ts.
export const GAMEPAD_BUTTON = gql`
  mutation gamepadButton($buttonIndex: Int!, $pressed: Boolean!, $watchdog: Boolean) {
    gamepadButton(buttonIndex: $buttonIndex, pressed: $pressed, watchdog: $watchdog)
  }
`;

export const GAMEPAD_AXIS = gql`
  mutation gamepadAxis($axisIndex: Int!, $value: Float!) {
    gamepadAxis(axisIndex: $axisIndex, value: $value)
  }
`;
