export default (fontSize: number = 1) => ({
  palette: {
    themePrimary: '#0095ff',
    themeLighterAlt: '#00060a',
    themeLighter: '#001829',
    themeLight: '#002d4d',
    themeTertiary: '#005999',
    themeSecondary: '#0083e0',
    themeDarkAlt: '#199fff',
    themeDark: '#3daeff',
    themeDarker: '#70c4ff',
    neutralLighterAlt: '#4d4d4d',
    neutralLighter: '#545454',
    neutralLight: '#606060',
    neutralQuaternaryAlt: '#676767',
    neutralQuaternary: '#6d6d6d',
    neutralTertiaryAlt: '#868686',
    neutralTertiary: '#c8c8c8',
    neutralSecondary: '#d0d0d0',
    neutralPrimaryAlt: '#dadada',
    neutralPrimary: '#ffffff',
    neutralDark: '#f4f4f4',
    black: '#f8f8f8',
    white: '#444444',
  },
  isInverted: true,
  fonts: {
    tiny: { fontSize: Math.round(10 * fontSize) },
    xSmall: { fontSize: Math.round(10 * fontSize) },
    small: { fontSize: Math.round(12 * fontSize) },
    smallPlus: { fontSize: Math.round(12 * fontSize) },
    medium: { fontSize: Math.round(14 * fontSize) },
    mediumPlus: { fontSize: Math.round(16 * fontSize) },
    large: { fontSize: Math.round(18 * fontSize) },
    xLarge: { fontSize: Math.round(20 * fontSize) },
    xLargePlus: { fontSize: Math.round(24 * fontSize) },
    xxLarge: { fontSize: Math.round(28 * fontSize) },
    xxLargePlus: { fontSize: Math.round(32 * fontSize) },
    superLarge: { fontSize: Math.round(42 * fontSize) },
    mega: { fontSize: Math.round(68 * fontSize) },
  },
  spacing: {
    s2: Math.round(4 * fontSize),
    s1: Math.round(8 * fontSize),
    m: Math.round(16 * fontSize),
    l1: Math.round(20 * fontSize),
    l2: Math.round(32 * fontSize),
  },
});
