export default (fontSize: number = 1) => ({
  palette: {
    themePrimary: '#0078d4',
    themeLighterAlt: '#f3f9fd',
    themeLighter: '#d0e7f8',
    themeLight: '#a9d3f2',
    themeTertiary: '#5ca9e5',
    themeSecondary: '#1a86d9',
    themeDarkAlt: '#006cbe',
    themeDark: '#005ba1',
    themeDarker: '#004377',
    neutralLighterAlt: '#f8f8f8',
    neutralLighter: '#f4f4f4',
    neutralLight: '#eaeaea',
    neutralQuaternaryAlt: '#dadada',
    neutralQuaternary: '#d0d0d0',
    neutralTertiaryAlt: '#c8c8c8',
    neutralTertiary: '#bab8b7',
    neutralSecondary: '#a3a2a0',
    neutralPrimaryAlt: '#8d8b8a',
    neutralPrimary: '#323130',
    neutralDark: '#605e5d',
    black: '#494847',
    white: '#ffffff',
  },
  fonts: {
    tiny: { fontSize: Math.round(10 * fontSize) },
    xSmall: { fontSize: Math.round(10 * fontSize) },
    small: { fontSize: Math.round(12 * fontSize) },
    smallPlus: { fontSize: Math.round(12 * fontSize) },
    medium: { fontSize: Math.round(14 * fontSize) },
    mediumPlus: { fontSize: Math.round(16 * fontSize) },
    large: { fontSize: Math.round(18 * fontSize) },
    xLarge: { fontSize: Math.round(20 * fontSize) },
    xLargePlus: { fontSize: Math.round(24 * fontSize) },
    xxLarge: { fontSize: Math.round(28 * fontSize) },
    xxLargePlus: { fontSize: Math.round(32 * fontSize) },
    superLarge: { fontSize: Math.round(42 * fontSize) },
    mega: { fontSize: Math.round(68 * fontSize) },
  },
  spacing: {
    s2: Math.round(4 * fontSize),
    s1: Math.round(8 * fontSize),
    m: Math.round(16 * fontSize),
    l1: Math.round(20 * fontSize),
    l2: Math.round(32 * fontSize),
  },
});
